################################################################################
# Region
################################################################################
variable "region" {
  description = "The AWS region"
  type        = string
}

variable "amazon_container_id" {
  description = "The Amazon Container ID"
  type        = string
  default     = "602401143452" #Default one is the most used. Watch out for the region.
}

################################################################################
# Networking
################################################################################
variable "vpc_cidr" {
  description = "The VPC CIDR"
  type        = string
}

variable "azs" {
  description = "The number of availability zones for the cluster"
  type        = number

}

variable "singleaz" {
  description = "The availability zone name to pin single-AZ resources (e.g., efs/mnt)"
  type        = string
  default     = null

}


variable "private_subnets" {
  description = "The private subnets"
  type        = list(string)

}

variable "public_subnets" {
  description = "The public subnets"
  type        = list(string)

}
################################################################################
# Cluster config
################################################################################
variable "cluster_name" {
  description = "Name of the EKS cluster"
  type        = string
  default     = "Cluster"
}

variable "instance_size" {
  description = "The instance size for the EKS cluster"
  type        = list(string)
  default     = ["m6i.large"]
}


variable "cluster_version" {
  description = "Kubernetes `<major>.<minor>` version to use for the EKS cluster (i.e.: `1.31`)"
  type        = string
  default     = "1.32"
}

variable "disk_size" {
  description = "The disk size in GB for the EKS worker nodes"
  type        = number
  default     = 75
}

################################################################################
# Dynamic node pools (eks managed node groups)
################################################################################

variable "node_pools" {
  description = "Map of node pools to create as EKS managed node groups"
  type = map(object({
    name          = string
    node_count    = number
    instance_size = string # maps to instance type
    disk_size     = number
    labels        = optional(map(string), {})
    taints = optional(list(object({
      key    = string
      value  = string
      effect = string # NoSchedule | PreferNoSchedule | NoExecute
    })), [])
  }))
  default = {
    default = {
      name          = "default"
      node_count    = 3
      instance_size = "m6i.large"
      disk_size     = 75
      labels        = {}
      taints        = []
    }
  }
}

variable "enable_cluster_creator_admin_permissions" {
  description = "Indicates whether or not the Amazon EKS public API server endpoint is enabled"
  type        = bool
  default     = true
}


variable "cluster_endpoint_public_access" {
  description = "Indicates whether or not the Amazon EKS public API server endpoint is enabled"
  type        = bool
  default     = true
}


################################################################################
# File System
################################################################################


variable "creation_token" {
  description = "A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform"
  type        = string
  default     = null
}


variable "encrypted" {
  description = "If `true`, the disk will be encrypted"
  type        = bool
  default     = true
}


variable "lifecycle_policy" {
  description = "A file system [lifecycle policy](https://docs.aws.amazon.com/efs/latest/ug/API_LifecyclePolicy.html) object"
  type        = any
  default     = {}
}



################################################################################
# Backup Policy
################################################################################

variable "create_backup_policy" {
  description = "Determines whether a backup policy is created"
  type        = bool
  default     = true
}

variable "enable_backup_policy" {
  description = "Determines whether a backup policy is `ENABLED` or `DISABLED`"
  type        = bool
  default     = true
}

################################################################################
# Replication Configuration
################################################################################

variable "create_replication_configuration" {
  description = "Determines whether a replication configuration is created"
  type        = bool
  default     = false
}

variable "replication_configuration_destination" {
  description = "A destination configuration block"
  type        = any
  default     = {}
}


################################################################################
# EBS controller service accounts
################################################################################



variable "ebs_csi_namespace" {
  description = "Namespace of the EBS CSI controller service account"
  type        = string
  default     = "kube-system"
}

variable "ebs_csi_service_account" {
  description = "Service account name of the EBS CSI controller"
  type        = string
  default     = "ebs-csi-controller-sa"
}

variable "attach_kms_permissions_to_ebs_role" {
  description = "Attach KMS key permissions to EBS CSI role when EKS has a KMS key configured"
  type        = bool
  default     = true
}



################################################################################
# Tags, it will merge with the default tags. 
################################################################################

variable "tags" {
  default = {
    Environment = "Production"
    Customer    = "Quix"
  }
  type = map(string)
}

################################################################################
# Route 53
################################################################################

variable "domain_name" {
  description = "The domain name for the Route 53 hosted zone"
  type        = string
  default     = "example.com"
}

variable "create_route53_zone" {
  description = "Whether to create a Route 53 hosted zone"
  type        = bool
  default     = false
}

################################################################################
# Cert Manager IAM Role
################################################################################

variable "create_cert_manager_role" {
  description = "Whether to create IAM role for cert-manager"
  type        = bool
  default     = false
}

variable "cert_manager_namespace" {
  description = "Namespace where cert-manager is deployed"
  type        = string
  default     = "quix-cert-manager"
}

variable "cert_manager_service_account" {
  description = "Service account name for cert-manager"
  type        = string
  default     = "cert-manager"
}

################################################################################
# Ansible driver installation (optional)
################################################################################

variable "enable_ansible_install" {
  description = "If true, generate playbook and run Ansible to install drivers"
  type        = bool
  default     = false
}

################################################################################
# Fetch credentials locally
################################################################################

variable "enable_credentials_fetch" {
  description = "Run aws eks get-credentials after creating the cluster"
  type        = bool
  default     = false
}
